apiVersion: v1
kind: Service
metadata:
  labels:
    app: adder
  name: adder
  namespace: default
  resourceVersion: "16401"
  selfLink: /api/v1/namespaces/default/services/adder
  uid: 87b4d43e-d557-4488-8e60-fd4c25d7878f
spec:
  clusterIP: 10.105.187.113
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adder
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
